Test API health

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -90,3 +90,25 @@ jobs:
 #        run: aws lambda update-function-code --function-name fastapi-sandbox-1 --s3-bucket karry-fastapi-sandbox --s3-key api.zip
       - name: Deploy new Lambda 2
         run: aws lambda update-function-code --function-name fastapi-sandbox-2 --s3-bucket karry-fastapi-sandbox --s3-key api.zip
+#      - name: Test URL
+#        uses: maxkomarychev/octions/octions/http/get@v0.0.3
+#        id: response
+#        with:
+#          url: "https://662nrjrc97.execute-api.us-east-2.amazonaws.com/v1/health"
+      - name: Test API health
+        uses: fjogeleit/http-request-action@v1
+        with:
+          url: "https://662nrjrc97.execute-api.us-east-2.amazonaws.com/v1/health"
+          method: 'GET'
+      - name: Check status code
+        run: |
+          if [ "${{ steps.response.outputs.status_code }}" != "200" ]; then
+            echo "Error: Expected status code 200, but got ${{ steps.response.outputs.status_code }}";
+            exit 1;
+          fi
+      - name: Check response body
+        run: |
+          if [ "${{ steps.response.outputs.body }}" != "{\"message\":\"healthy\"}" ]; then
+            echo "Error: Unexpected response body";
+            exit 1;
+          fi
