Fixing health test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -98,19 +98,24 @@ jobs:
       - name: Test API health
         uses: fjogeleit/http-request-action@v1
         with:
+          id: health
           url: "https://662nrjrc97.execute-api.us-east-2.amazonaws.com/v1/health"
           method: 'GET'
-          status-code: "200"
-          body-includes: "Wrong output"
-#      - name: Check status code
-#        run: |
-#          if [ "${{ steps.response.outputs.status_code }}" != "200" ]; then
-#            echo "Error: Expected status code 200, but got ${{ steps.response.outputs.status_code }}";
-#            exit 1;
-#          fi
-#      - name: Check response body
-#        run: |
-#          if [ "${{ steps.response.outputs.body }}" != "{\"message\":\"healthy\"}" ]; then
-#            echo "Error: Unexpected response body";
-#            exit 1;
-#          fi
+          retry: 5
+      - name: Show Response
+        run: |
+          echo ${{ steps.health.outputs.response }}
+          echo ${{ steps.health.outputs.headers }}
+          echo ${{ fromJson(steps.health.outputs.response).status_code }}
+      - name: Check status code
+        run: |
+          if [ "${{ steps.health.outputs.status_code }}" != "200" ]; then
+            echo "Error: Expected status code 200, but got ${{ steps.health.outputs.status_code }}";
+            exit 1;
+          fi
+      - name: Check response body
+        run: |
+          if [ "${{ steps.health.outputs.body }}" != "{\"message\":\"healthy\"}" ]; then
+            echo "Error: Unexpected response body";
+            exit 1;
+          fi
